# Copyright The OpenTelemetry Authors
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     https://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#
"""Tests for autogenerated-section and HTML comment removal in published README markdown."""

from explorer_db_builder.readme_sanitizer import sanitize_readme


class TestRemovesAutogeneratedSection:
    """The status block is rendered from component metadata, so the README tab drops it."""

    def test_removes_the_whole_section_not_just_the_markers(self):
        content = (
            "<!-- status autogenerated section -->\n"
            "# Batch Processor\n"
            "| Status | |\n"
            "| ------ |-|\n"
            "| Stability | [beta] |\n"
            "\n"
            "[beta]: https://example.com/stability\n"
            "<!-- end autogenerated section -->\n"
            "\n"
            "The batch processor accepts spans.\n"
        )

        assert sanitize_readme(content) == "The batch processor accepts spans.\n"

    def test_removes_a_section_that_carries_the_component_description(self):
        # 159 of 328 collector READMEs put prose inside the section; the detail
        # page already renders it from component.description.
        content = (
            "<!-- status autogenerated section -->\n"
            "# ACK Extension\n"
            "\n"
            "This extension allows acking of data upon successful processing.\n"
            "\n"
            "| Status | |\n"
            "<!-- end autogenerated section -->\n"
            "Body text.\n"
        )

        assert sanitize_readme(content) == "Body text.\n"

    def test_restores_a_link_definition_the_body_still_references(self):
        # countconnector defines [Exporter Pipeline Type] inside the section and
        # uses it again further down.
        content = (
            "<!-- status autogenerated section -->\n"
            "# Count Connector\n"
            "| [Exporter Pipeline Type] | [Stability Level] |\n"
            "\n"
            "[Exporter Pipeline Type]: https://example.com/exporter\n"
            "[Stability Level]: https://example.com/stability\n"
            "<!-- end autogenerated section -->\n"
            "\n"
            "See [Exporter Pipeline Type] for details.\n"
        )

        result = sanitize_readme(content)

        assert "See [Exporter Pipeline Type] for details." in result
        assert "[Exporter Pipeline Type]: https://example.com/exporter" in result
        # Unreferenced definitions stay dropped.
        assert "Stability Level" not in result

    def test_restores_a_definition_whose_label_differs_only_by_case(self):
        content = (
            "<!-- status autogenerated section -->\n"
            "[Stability Level]: https://example.com/stability\n"
            "<!-- end autogenerated section -->\n"
            "See [stability level].\n"
        )

        assert "[Stability Level]: https://example.com/stability" in sanitize_readme(content)

    def test_restores_a_definition_whose_label_differs_only_by_whitespace(self):
        # CommonMark folds internal whitespace when matching labels, so a use split
        # across lines still points at the definition.
        content = (
            "<!-- status autogenerated section -->\n"
            "[Exporter Pipeline Type]: https://example.com/exporter\n"
            "<!-- end autogenerated section -->\n"
            "See [Exporter\nPipeline   Type] for details.\n"
        )

        assert "[Exporter Pipeline Type]: https://example.com/exporter" in sanitize_readme(content)

    def test_does_not_restore_a_definition_used_only_inside_a_code_fence(self):
        # Bracketed text is common in code samples. Restoring on that evidence would
        # silently turn matching prose elsewhere into a link.
        content = (
            "<!-- status autogenerated section -->\n"
            "[beta]: https://example.com/beta\n"
            "<!-- end autogenerated section -->\n"
            "Prose with no reference.\n"
            "\n"
            "```python\n"
            "x = data[beta]\n"
            "```\n"
        )

        assert "https://example.com/beta" not in sanitize_readme(content)

    def test_matches_case_and_whitespace_variants_of_the_markers(self):
        content = "<!--  Status Autogenerated Section  -->\n# T\n<!--end autogenerated section-->\nBody.\n"

        assert sanitize_readme(content) == "Body.\n"

    def test_unpaired_start_marker_falls_back_to_dropping_just_the_comment(self):
        content = "<!-- status autogenerated section -->\n# Title\n\nBody.\n"

        assert sanitize_readme(content) == "# Title\n\nBody.\n"

    def test_leaves_a_section_inside_a_code_fence_alone(self):
        content = "```md\n<!-- status autogenerated section -->\n# Example\n<!-- end autogenerated section -->\n```\n"

        assert sanitize_readme(content) == content


class TestStripsComments:
    def test_removes_tooling_directives(self):
        content = "<!-- markdown-link-check-disable-next-line -->\n[link](http://example.com)\n"

        assert sanitize_readme(content) == "[link](http://example.com)\n"

    def test_drops_comment_only_line_rather_than_leaving_a_blank(self):
        content = "a\n<!-- note -->\nb\n"

        assert sanitize_readme(content) == "a\nb\n"

    def test_keeps_prose_around_an_inline_comment(self):
        content = "Some text <!-- hidden --> more text\n"

        assert sanitize_readme(content) == "Some text  more text\n"

    def test_removes_a_multi_line_comment_whole(self):
        content = "before\n<!-- line one\nline two\nline three -->\nafter\n"

        assert sanitize_readme(content) == "before\nafter\n"

    def test_removes_two_comments_on_one_line_independently(self):
        content = "<!-- a -->keep<!-- b -->\n"

        assert sanitize_readme(content) == "keep\n"

    def test_leaves_content_without_comments_byte_identical(self):
        content = "# Title\n\nSome prose with a `<!--` fragment that never closes.\n"

        assert sanitize_readme(content) == content

    def test_handles_empty_input(self):
        assert sanitize_readme("") == ""


class TestPreservesCodeFences:
    def test_keeps_comments_inside_a_backtick_fence(self):
        # pom.xml comments are part of the sample the reader copies.
        content = (
            "<!-- status autogenerated section -->\n"
            "# Spring Web MVC\n"
            "\n"
            "```xml\n"
            "<!-- OpenTelemetry instrumentation -->\n"
            "<dependency>\n"
            "  <artifactId>opentelemetry-spring-webmvc</artifactId>\n"
            "</dependency>\n"
            "```\n"
        )

        result = sanitize_readme(content)

        assert "status autogenerated section" not in result
        assert "<!-- OpenTelemetry instrumentation -->" in result
        assert result == (
            "# Spring Web MVC\n"
            "\n"
            "```xml\n"
            "<!-- OpenTelemetry instrumentation -->\n"
            "<dependency>\n"
            "  <artifactId>opentelemetry-spring-webmvc</artifactId>\n"
            "</dependency>\n"
            "```\n"
        )

    def test_keeps_comments_inside_a_tilde_fence(self):
        content = "~~~xml\n<!-- kept -->\n~~~\n<!-- dropped -->\n"

        assert sanitize_readme(content) == "~~~xml\n<!-- kept -->\n~~~\n"

    def test_keeps_comments_inside_an_indented_fence(self):
        content = "- item:\n\n   ```xml\n   <!-- kept -->\n   ```\n\n<!-- dropped -->\n"

        result = sanitize_readme(content)

        assert "<!-- kept -->" in result
        assert "dropped" not in result

    def test_scrubs_prose_between_two_fences(self):
        content = "```\na\n```\n<!-- dropped -->\n```\nb\n```\n"

        assert sanitize_readme(content) == "```\na\n```\n```\nb\n```\n"

    def test_a_longer_closing_fence_still_closes_the_block(self):
        content = "```\n<!-- kept -->\n````\n<!-- dropped -->\n"

        result = sanitize_readme(content)

        assert "<!-- kept -->" in result
        assert "dropped" not in result

    def test_a_different_fence_char_does_not_close_the_block(self):
        content = "```\n~~~\n<!-- kept -->\n```\n<!-- dropped -->\n"

        result = sanitize_readme(content)

        assert "<!-- kept -->" in result
        assert "dropped" not in result

    def test_an_info_string_line_does_not_close_the_block(self):
        content = "```xml\n```python\n<!-- kept -->\n```\n<!-- dropped -->\n"

        result = sanitize_readme(content)

        assert "<!-- kept -->" in result
        assert "dropped" not in result

    def test_unterminated_fence_leaves_the_rest_untouched(self):
        # Malformed input: treat everything after the opener as code.
        content = "intro\n```xml\n<!-- kept -->\n"

        assert sanitize_readme(content) == content

    def test_document_starting_with_a_fence_gains_no_leading_blank_line(self):
        content = "```\nx\n```\n<!-- dropped -->\n"

        assert sanitize_readme(content) == "```\nx\n```\n"
