# Copyright The OpenTelemetry Authors
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     https://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#
"""Cleanup applied to upstream README markdown before it is published to the database.

Removes the autogenerated status section (title, stability/distribution table,
badges, code owners - all of which the explorer already renders from component
metadata) and any HTML comments left over.

Both rules skip fenced code blocks: Java instrumentation READMEs embed pom.xml
and logback.xml snippets whose comments are part of the sample being copied.
"""

import re

_SECTION_RE = re.compile(
    r"<!--\s*status autogenerated section\s*-->.*?<!--\s*end autogenerated section\s*-->[ \t]*\n?",
    re.DOTALL | re.IGNORECASE,
)

# DOTALL so a comment spanning lines is removed whole; non-greedy so two comments
# on one line don't collapse into a single match.
_COMMENT_RE = re.compile(r"<!--.*?-->", re.DOTALL)

# CommonMark fence: up to 3 leading spaces, then 3+ backticks or tildes.
_FENCE_RE = re.compile(r"^ {0,3}(?P<fence>`{3,}|~{3,})(?P<info>.*)$")

_REF_DEF_RE = re.compile(r"^ {0,3}\[(?P<label>[^\]]+)\]:[ \t]*\S.*$", re.MULTILINE)

# Deliberately loose - a false positive only keeps an unused definition, which
# renders as nothing.
_REF_USE_RE = re.compile(r"\[([^\]\[]+)\](?![(:])")

# Marks where a comment was, so a line left with nothing else can be dropped
# rather than becoming blank. NUL never appears in real markdown.
_REMOVED = "\x00"


def _clean(chunk: str, dropped_refs: dict[str, str]) -> list[str]:
    """Strip sections and comments from a run of non-code lines.

    Link definitions carried off with a removed section are recorded in
    ``dropped_refs`` for the caller to restore if still referenced.
    """
    if "<!--" not in chunk:
        return chunk.split("\n")

    def record_refs(match: re.Match[str]) -> str:
        for definition in _REF_DEF_RE.finditer(match.group(0)):
            dropped_refs.setdefault(definition.group("label").lower(), definition.group(0).strip())
        return ""

    chunk = _SECTION_RE.sub(record_refs, chunk)

    lines = []
    for line in _COMMENT_RE.sub(_REMOVED, chunk).split("\n"):
        if _REMOVED in line:
            if not line.replace(_REMOVED, "").strip():
                continue
            line = line.replace(_REMOVED, "")
        lines.append(line)
    return lines


def sanitize_readme(markdown: str) -> str:
    """Remove autogenerated status sections and HTML comments from README markdown.

    Args:
        markdown: Raw README content.

    Returns:
        The cleaned content. Fenced code blocks pass through byte for byte.
    """
    if "<!--" not in markdown:
        return markdown

    out: list[str] = []
    prose: list[str] = []
    dropped_refs: dict[str, str] = {}
    fence_char: str | None = None
    fence_len = 0

    def flush() -> None:
        # Guarded: cleaning an empty buffer would yield a spurious blank line.
        if prose:
            out.extend(_clean("\n".join(prose), dropped_refs))
            prose.clear()

    for line in markdown.split("\n"):
        match = _FENCE_RE.match(line)

        if fence_char is None:
            if match:
                flush()
                fence_char = match.group("fence")[0]
                fence_len = len(match.group("fence"))
                out.append(line)
            else:
                prose.append(line)
            continue

        out.append(line)
        if (
            match
            and match.group("fence")[0] == fence_char
            and len(match.group("fence")) >= fence_len
            and not match.group("info").strip()
        ):
            fence_char = None

    # An unterminated fence buffers nothing - its lines already went to `out`
    # verbatim, the safe reading of malformed input.
    flush()

    # lstrip: removing a leading section otherwise leaves the blank line that
    # followed it, so the file would open on whitespace.
    return _restore_used_refs("\n".join(out).lstrip("\n"), dropped_refs)


def _restore_used_refs(markdown: str, dropped_refs: dict[str, str]) -> str:
    """Re-append link definitions the surviving content still references.

    A status section owns the definitions for its own badge rows, but a body
    occasionally reuses one further down (countconnector's
    ``[Exporter Pipeline Type]``), which would otherwise render as literal
    bracketed text.
    """
    if not dropped_refs:
        return markdown

    used = {label.lower() for label in _REF_USE_RE.findall(markdown)}
    restored = [definition for label, definition in dropped_refs.items() if label in used]
    if not restored:
        return markdown

    return markdown.rstrip("\n") + "\n\n" + "\n".join(restored) + "\n"
