# Copyright The OpenTelemetry Authors
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     https://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#
"""Cleanup applied to upstream README markdown before it is published to the database.

Two things are removed:

1. **Autogenerated status sections.** Every collector component README opens with
   a block fenced by ``<!-- status autogenerated section -->`` and
   ``<!-- end autogenerated section -->`` holding the component's title, status
   table (stability, distributions, issue/coverage badges, code owners) and the
   link definitions those rows use. The explorer renders all of that from the
   component's own metadata, so republishing it in the README tab duplicates the
   page around it.

2. **HTML comments.** Comments are invisible on GitHub but leak into the
   explorer's rendered output - tooling directives such as
   ``<!-- markdown-link-check-disable -->``, stray editorial notes, and the
   section markers themselves in any README where they don't pair up.

Comments inside fenced code blocks are deliberately preserved: Java
instrumentation READMEs embed ``pom.xml`` and ``logback.xml`` snippets whose
``<!-- ... -->`` comments are part of the sample the reader is meant to copy.
For the same reason both rules only apply outside code fences.
"""

import re

# The section markers are emitted by upstream tooling with fixed wording; the
# tolerant whitespace/case handling is only so a hand-edited README still matches.
_SECTION_RE = re.compile(
    r"<!--\s*status autogenerated section\s*-->.*?<!--\s*end autogenerated section\s*-->[ \t]*\n?",
    re.DOTALL | re.IGNORECASE,
)

# DOTALL so a comment that spans lines is removed whole. Non-greedy so adjacent
# comments on one line don't collapse into a single match.
_COMMENT_RE = re.compile(r"<!--.*?-->", re.DOTALL)

# CommonMark fence: up to 3 leading spaces, then 3+ backticks or tildes.
_FENCE_RE = re.compile(r"^ {0,3}(?P<fence>`{3,}|~{3,})(?P<info>.*)$")

# A link reference definition line, e.g. "[beta]: https://example.com/spec".
_REF_DEF_RE = re.compile(r"^ {0,3}\[(?P<label>[^\]]+)\]:[ \t]*\S.*$", re.MULTILINE)

# A use of a link reference, e.g. "[beta]" or the label half of "[text][beta]".
# Deliberately loose - a false positive only means an unused definition survives,
# and unused definitions render as nothing.
_REF_USE_RE = re.compile(r"\[([^\]\[]+)\](?![(:])")

# Stands in for a removed comment so that lines left with nothing but removed
# comments can be dropped entirely, while lines with surrounding prose are kept.
# NUL never appears in real markdown, so it cannot collide with content.
_REMOVED = "\x00"


def _clean(chunk: str, dropped_refs: dict[str, str]) -> list[str]:
    """Strip autogenerated sections and HTML comments from a run of non-code lines.

    Link definitions carried away with a removed section are recorded in
    ``dropped_refs`` (keyed by lowercased label) so the caller can restore any
    the surviving document still points at.

    Returns the surviving lines. A line consisting only of comments (and
    whitespace) is dropped rather than left behind as a blank line.
    """
    if "<!--" not in chunk:
        return chunk.split("\n")

    def record_refs(match: re.Match[str]) -> str:
        for definition in _REF_DEF_RE.finditer(match.group(0)):
            dropped_refs.setdefault(definition.group("label").lower(), definition.group(0).strip())
        return ""

    chunk = _SECTION_RE.sub(record_refs, chunk)

    lines = []
    for line in _COMMENT_RE.sub(_REMOVED, chunk).split("\n"):
        if _REMOVED in line:
            # Whole-line comment: drop it. Inline comment: keep the prose around it.
            if not line.replace(_REMOVED, "").strip():
                continue
            line = line.replace(_REMOVED, "")
        lines.append(line)
    return lines


def sanitize_readme(markdown: str) -> str:
    """Remove autogenerated status sections and HTML comments from README markdown.

    Args:
        markdown: Raw README content.

    Returns:
        The cleaned content. Fenced code blocks - including any comments inside
        them - are passed through byte for byte.
    """
    if "<!--" not in markdown:
        return markdown

    out: list[str] = []
    prose: list[str] = []
    dropped_refs: dict[str, str] = {}
    fence_char: str | None = None
    fence_len = 0

    def flush() -> None:
        # Guarded: cleaning an empty buffer would yield a spurious blank line.
        if prose:
            out.extend(_clean("\n".join(prose), dropped_refs))
            prose.clear()

    for line in markdown.split("\n"):
        match = _FENCE_RE.match(line)

        if fence_char is None:
            if match:
                flush()
                fence_char = match.group("fence")[0]
                fence_len = len(match.group("fence"))
                out.append(line)
            else:
                prose.append(line)
            continue

        out.append(line)
        # A closing fence uses the same character, is at least as long as the
        # opener, and carries no info string.
        if (
            match
            and match.group("fence")[0] == fence_char
            and len(match.group("fence")) >= fence_len
            and not match.group("info").strip()
        ):
            fence_char = None

    # An unterminated fence leaves nothing buffered - its lines already went to
    # `out` verbatim, which is the safe reading of malformed input.
    flush()

    # Removing a leading section leaves the blank line that followed it, so the
    # published file would open on whitespace. Renders the same either way, but
    # the raw markdown is also served to agents and read in diffs.
    return _restore_used_refs("\n".join(out).lstrip("\n"), dropped_refs)


def _restore_used_refs(markdown: str, dropped_refs: dict[str, str]) -> str:
    """Re-append link definitions that the surviving content still references.

    A status section owns the definitions for its own badge rows, but a README
    body occasionally reuses one further down (e.g. countconnector's
    ``[Exporter Pipeline Type]``). Dropping those would render the reference as
    literal bracketed text, so they are restored at the end of the document,
    where markdown treats them the same as anywhere else.
    """
    if not dropped_refs:
        return markdown

    used = {label.lower() for label in _REF_USE_RE.findall(markdown)}
    restored = [definition for label, definition in dropped_refs.items() if label in used]
    if not restored:
        return markdown

    return markdown.rstrip("\n") + "\n\n" + "\n".join(restored) + "\n"
