globs:
  - "**/*.md"
ignores:
  - node_modules
  - CLAUDE.md
  - "**/tmp_repos/**"

config:
  default: true
  MD013:
    line_length: 120
    tables: false
  MD033:
    allowed_elements:
      - details
      - summary
  MD041: false