/*
 * Copyright The OpenTelemetry Authors
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      https://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
import { describe, it, expect } from "vitest";
import type { ConfigNode } from "@/types/configuration";
import type { ConfigurationBuilderState } from "@/types/configuration-builder";
import { generateYaml } from "./yaml-generator";

const emptySchema: ConfigNode = {
  controlType: "group",
  key: "root",
  label: "Root",
  path: "",
  children: [],
};

const emptyState: ConfigurationBuilderState = {
  version: "1.0.0",
  values: {},
  enabledSections: {},
  validationErrors: {},
  isDirty: false,
};

describe("generateYaml", () => {
  it("generates default header and respects override", () => {
    const today = new Date().toISOString().slice(0, 10);

    const defaultOutput = generateYaml(emptyState, emptySchema);
    expect(defaultOutput).toContain("# OpenTelemetry SDK Configuration");
    expect(defaultOutput).toContain(`# Generated by Ecosystem Explorer on ${today}`);
    expect(defaultOutput).toContain("# Schema version: 1.0.0");

    const overridden = generateYaml(emptyState, emptySchema, { header: "# custom" });
    expect(overridden.startsWith("# custom\n")).toBe(true);
    expect(overridden).not.toContain("# OpenTelemetry SDK Configuration");
  });
});
