/*
 * Copyright The OpenTelemetry Authors
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      https://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
import type { ConfigurationBuilderState } from "@/types/javaagent";
import { flatToDeclarative } from "./config-name-converter";
import { generateSdkYaml } from "./sdk-yaml-generator";

type NestedConfig = Record<string, unknown>;

function setNestedValue(obj: NestedConfig, path: string[], value: unknown): void {
  let current = obj;

  for (let i = 0; i < path.length - 1; i++) {
    const key = path[i];
    if (!(key in current)) {
      current[key] = {};
    }
    current = current[key] as NestedConfig;
  }

  const lastKey = path[path.length - 1];
  current[lastKey] = value;
}

function formatYamlValue(value: unknown): string {
  if (typeof value === "boolean") {
    return String(value);
  }
  if (typeof value === "number") {
    return String(value);
  }
  if (typeof value === "string") {
    if (value === "") {
      return '""';
    }
    if (value.includes(",") || value.includes(":") || value.includes("#")) {
      return `"${value}"`;
    }
    return value;
  }
  if (Array.isArray(value)) {
    if (value.length === 0) {
      return "[]";
    }
    return `[${value.map(formatYamlValue).join(", ")}]`;
  }
  return String(value);
}

function serializeYaml(obj: NestedConfig, indent = 0): string {
  const lines: string[] = [];
  const indentStr = "  ".repeat(indent);

  const sortedKeys = Object.keys(obj).sort((a, b) => a.localeCompare(b));

  for (const key of sortedKeys) {
    const value = obj[key];
    if (typeof value === "object" && value !== null && !Array.isArray(value)) {
      if (Object.keys(value as NestedConfig).length === 0) continue;
      lines.push(`${indentStr}${key}:`);
      lines.push(serializeYaml(value as NestedConfig, indent + 1));
    } else {
      lines.push(`${indentStr}${key}: ${formatYamlValue(value)}`);
    }
  }

  return lines.join("\n");
}

export function generateYamlFile(state: ConfigurationBuilderState): string {
  const lines: string[] = [];

  lines.push("# OpenTelemetry Java Agent Configuration");
  lines.push("# Generated by Ecosystem Explorer");
  lines.push(`# Version: ${state.version}`);
  lines.push("");

  const instrumentations = Array.from(state.selectedInstrumentations.values());

  // Build instrumentation config block
  const seenKeys = new Set<string>();
  const rootConfig: NestedConfig = {};

  for (const instrumentation of instrumentations) {
    const configs =
      instrumentation.data.configurations?.filter((config) =>
        instrumentation.enabledConfigs.has(config.name)
      ) || [];

    for (const config of configs) {
      const declarativeName = flatToDeclarative(config.name);
      if (!seenKeys.has(declarativeName)) {
        seenKeys.add(declarativeName);
        const pathSegments = declarativeName.split(".");
        setNestedValue(rootConfig, pathSegments, config.default);
      }
    }
  }

  const hasInstrumentation = Object.keys(rootConfig).length > 0;
  const hasSdk = true; // SDK config is always included

  if (hasSdk) {
    lines.push("# --- SDK Configuration ---");
    lines.push(generateSdkYaml(state.sdkConfig));
  }

  if (hasInstrumentation) {
    if (hasSdk) lines.push("");
    lines.push("# --- Instrumentation Configuration ---");
    lines.push(serializeYaml(rootConfig));
  }

  if (!hasSdk && !hasInstrumentation) {
    lines.push("# No configurations selected");
  }

  return lines.join("\n");
}
